version: '1.2.1.{build}'

environment:
  matrix:
    - project_name: samples/tinydir.sln
    - project_name: tests/tinydir_tests.sln

# Only build if file changes here
only_commits:
  files:
    - samples/
    - tests/
    - appveyor.yml
    - tinydir.h

image: Visual Studio 2015

build:
  project: $(project_name)

before_build:
  - cd samples && cmake -G "Visual Studio 14 2015" . && cd ..
  - cd tests && cmake -G "Visual Studio 14 2015" . && cd ..

after_build:
  - cd tests && ctest --output-on-failure . && cd ..
